# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: hyxos.io
email: donnie@hyxos.ca
description: > # this means to ignore newlines until "baseurl:"
  A Toronto area developer writes stuff about things, and things about stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hyxos.ca" # the base hostname & protocol for your site
twitter_username: hyxos
github_username:  hyxos

# Build settings
markdown: kramdown
